#!/usr/bin/env bash
# Usage:
#   ./bump_version.sh patch   → 1.0.0 → 1.0.1
#   ./bump_version.sh minor   → 1.0.1 → 1.1.0
#   ./bump_version.sh major   → 1.1.0 → 2.0.0

set -e

# Always run from the repo root regardless of where the script is called from
cd "$(dirname "$0")"

PART=${1:-patch}
PUBSPEC="pubspec.yaml"
VERSION_FILE="lib/version.dart"

# Read current version and build number from pubspec.yaml
CURRENT=$(grep -m1 '^version:' "$PUBSPEC" | sed 's/^version:[[:space:]]*//')
VERSION=$(echo "$CURRENT" | cut -d'+' -f1)
BUILD=$(echo "$CURRENT" | cut -d'+' -f2)

MAJOR=$(echo "$VERSION" | cut -d'.' -f1)
MINOR=$(echo "$VERSION" | cut -d'.' -f2)
PATCH=$(echo "$VERSION" | cut -d'.' -f3)

case "$PART" in
  major) MAJOR=$((MAJOR + 1)); MINOR=0; PATCH=0 ;;
  minor) MINOR=$((MINOR + 1)); PATCH=0 ;;
  patch) PATCH=$((PATCH + 1)) ;;
  *) echo "Usage: $0 [major|minor|patch]"; exit 1 ;;
esac

NEW_VERSION="$MAJOR.$MINOR.$PATCH"
NEW_BUILD=$((BUILD + 1))
NEW_FULL="$NEW_VERSION+$NEW_BUILD"

# Update pubspec.yaml (portable: works on both Linux and macOS)
sed -i.bak "s/^version: .*/version: $NEW_FULL/" "$PUBSPEC" && rm -f "$PUBSPEC.bak"

# Update lib/version.dart
cat > "$VERSION_FILE" <<EOF
// Auto-generated by bump_version.sh — do not edit manually
const String appVersion = '$NEW_VERSION';
const int appBuildNumber = $NEW_BUILD;
EOF

echo "Version bumped: $CURRENT → $NEW_FULL"

# Git commit only version files (no other staged changes captured)
git commit "$PUBSPEC" "$VERSION_FILE" -m "chore: bump version to $NEW_FULL"
git tag -a "v$NEW_VERSION" -m "Release v$NEW_VERSION"

echo "Tagged: v$NEW_VERSION"
echo "Push with: git push && git push --tags"
